---
modules-search: [ local ]

instances:
  - module: shellprocess
    id: bootc-install
    config: shellprocess-bootc-install.conf

sequence:
- show:
  - welcome
  - installmode
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - shellprocess@bootc-install
  - umount
- show:
  - finished

branding: xfce-aerolike
prompt-install: true
dont-chroot: true
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
