---
createHybridBootloaderLayout: true
enableLuksAutomatedPartitioning: false

efi:
    mountPoint: "/boot/efi"
    recommendedSize: 300MiB
    minimumSize: 32MiB
    label: "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

luksGeneration: luks1
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none

defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs", "f2fs", "bcachefs"]

essentialMounts: [ "live-*", "control", "ventoy" ]
