---
dontChroot: false
timeout: 600
verbose: true
script:
    - command: "/usr/bin/install-xfce-aerolike"
      timeout: 600
      verbose: true
i18n:
    name: "Install xfce-aerolike system"
    name[en]: "Install xfce-aerolike system"
