server:
  interface: 127.0.0.1
  interface: ::1
  access-control: 127.0.0.0/8 allow
  access-control: ::1 allow
  chroot: ""
  hide-identity: yes
  hide-version: yes
  prefetch: yes
  prefetch-key: yes
  auto-trust-anchor-file: /etc/unbound/root.key
  do-not-query-localhost: no

remote-control:
  control-enable: no
